config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  root 'weather#show'

  get 'search_weather', to: 'weather#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/cache_helper.rb
module CacheHelper
  extend ActiveSupport::Concern

  CACHE_EXPIRATION_TIME = 30.minutes

  def cache_value(key, value, expiration = CACHE_EXPIRATION_TIME)
    Rails.cache.write(key, value, expires_in: expiration)
  end

  def cached_value(key)
    Rails.cache.fetch(key)
  end

  def fetch_cached_value(key)
    Rails.cache.read(key)
  end

  def cache_or_fetch(key, value, expiration = CACHE_EXPIRATION_TIME)
    if fetch_cached_value(key).present?
      cached_value(key)
    else
      cache_value(key, value, expiration)
      value
    end
  end
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  include CacheHelper

  before_action :set_address, only: %i[show]

  def show
    return if @address.blank?

    service = WeatherService.new(@address)
    @weather_data = service.fetch_weather_data
    Rails.logger.info(@address)
    if @weather_data.blank?
      flash.now[:error] = 'Weather is not avaliable for this address'
      return
    end
    cache_value(service.zipcode, @weather_data)
    @lowest_temperature, @highest_temperature, @current_temperature = @weather_data
  rescue StandardError => e
    flash.now[:error] = "class: #{e.class}, #{e.message}"
  end

  private

  def weather_params
    params.permit(:address, :commit, :controller, :action)
  end

  def set_address
    @address = weather_params[:address]
    nil if @address.blank?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherWebApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_textfield.html.erb
<%= f.label name %>
<%= f.text_field name, value: @address %>

app/views/weather/new.html.erb
<%= form_with url: search_weather_path, method: :get, local: true do |f| %>
  <%= render partial: "shared/textfield", locals: { f: f, name: :address, prev_value: @address} %>
  <%= f.submit "Search" %>
<% end %>

app/views/weather/show.html.erb
<% if flash[:error].present? %>
  <p class="error">Error: <%= flash[:error] %></p>
<% end %>

<%= form_with url: search_weather_path, method: :get, local: true do |f| %>
  <%= render partial: "shared/textfield", locals: { f: f, name: :address} %>
  <%= f.submit "Search" %>
<% end %>

<% if flash[:error].blank? && @weather_data.present? %>
  <h2>Location: <%= @address %> </h2>
  <p>Highest Temperature: <%= @highest_temperature %></p>
  <p>Lowest Temperature: <%= @lowest_temperature %></p>
  <p>Current Temperature: <%= @current_temperature %></p>
<% end %>